spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3377/breadgood?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: test1
    password: 1234
    hikari:
      poolName: Hikari
      maximum-pool-size: 3
      minimum-idle: 3
      max-lifetime: 57600
      connection-timeout: 57600
      idle-timeout: 30000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  # JPA Settings
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate.format_sql: true

