# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ feature/18 ]
  pull_request:
    branches: [ feature/18 ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x ./breadgood-server/gradlew

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./breadgood-server

    - name: Grant execute permission for scripts
      run: chmod +x ./scripts

    - name: Check build file
      run:  sh -c "./scripts/test.sh"

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build docker-compose
      run: docker-compose -f docker-compose.yml build

    - name: push docker image
      run: docker-compose -f docker-compose.yml push
      
    - name: Trigger the CodeDeploy in EC2 instance
      run: aws deploy --region ap-northeast-2 create-deployment --application-name breadgood-test --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name breadgood-test --github-location repository=bell204/breadgood,commitId=8f1fae74afa02296c28647db719be90795f44c71      
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        Default_region_name: ap-northeast-2
